services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__WarehouseDb: Host=postgres;Port=5432;Database=severstal_warehouse;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: severstal_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

